<a href="https://colab.research.google.com/github/Manjeet583/apnacollege-demo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**3) #exponent
print(np.sqrt(a)) # to find the square root
print(np.power(a,5)) # for n exponent
arr = np.array([10,20,20,30,40,50]) # defining 2d array
print(np.mean(arr)) # to find the average
print(np.median(arr)) # to find the median
print(np.max(arr)) # to find the max value
print(np.min(arr)) # to find the min value
print(np.sum(arr)) # total value
print(np.std(arr)) # standard deviation
print(np.var(arr)) # variance
arr2 = np.array([1,2,3,4,5,6])
print(arr2.reshape(2,3))





[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[ 1  8 27]
[1.         1.41421356 1.73205081]
[  1  32 243]
28.333333333333332
25.0
50
10
170
13.43709624716425
180.55555555555557
[[1 2 3]
 [4 5 6]]


In [18]:
arr = np.array([[1,2],[3,4]])

print(arr.flatten())

[1 2 3 4]


In [19]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(1,11) # array in paricular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.random.rand(5) # give random numbers below 1

array([0.3127183 , 0.43337761, 0.82307098, 0.26734891, 0.77612142])

In [27]:
np.random.randint(1,100,10) # give random integers

array([55, 65, 68, 93,  2, 29, 49, 10, 14, 57])

In [30]:
arr = np.array([5,2,9,1])
print(np.sort(arr))

[1 2 5 9]


In [31]:
arr = np.array([1,2,2,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [36]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,6))

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [37]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]
